name: Windows Screenshot Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  capture-screenshots:
    runs-on: windows-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install dependencies (if needed)
      - name: Set up environment
        run: |
          echo Setting up environment...
          # Add any required setup steps here

      # Take a screenshot
      - name: Capture Screenshot
        run: |
          mkdir screenshots
          Add-Type -AssemblyName System.Windows.Forms
          $bmp = New-Object Drawing.Bitmap([System.Windows.Forms.Screen]::PrimaryScreen.Bounds.Width, [System.Windows.Forms.Screen]::PrimaryScreen.Bounds.Height)
          $graphics = [Drawing.Graphics]::FromImage($bmp)
          $graphics.CopyFromScreen([System.Windows.Forms.Screen]::PrimaryScreen.Bounds.Location, [Drawing.Point]::Empty, $bmp.Size)
          $screenshotPath = "screenshots/screenshot_$(Get-Date -Format 'yyyy-MM-dd_HH-mm-ss').png"
          $bmp.Save($screenshotPath, [Drawing.Imaging.ImageFormat]::Png)
          Write-Host "Screenshot saved to $screenshotPath"

      # Upload the screenshots as artifacts
      - name: Upload Screenshots
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: screenshots/
